[package]
authors = ["James Tease <james@jamestease.co.uk>"]
name = "flake"
version = "0.1.0"

[dependencies]
actix = "0.5.7"
actix-web = "0.6"
env_logger = "0.5.10"
sha2 = "0.7.1"
tera = "0.11.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.snowflake]
path = "./snowflake"
